"""empty message

Revision ID: 52daa53c4fa9
Revises: 8a2a9ec4c220
Create Date: 2024-07-24 16:34:17.082908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52daa53c4fa9'
down_revision = '8a2a9ec4c220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
